services:
  dotnet-sdk:
    image: amaic/devcontainer-dotnet-sdk:${DOTNET_VERSION}
    build:
      context: .
      dockerfile: dockerfile
      args:
        - PLATFORM=${PLATFORM}
        - DOTNET_VERSION=${DOTNET_VERSION}
