services:
  dotnet-sdk-x64-8:
    # https://dotnet.microsoft.com/en-us/download/dotnet/8.0
    image: amaic/devcontainer-dotnet-sdk:x64-8
    build:
      context: .
      dockerfile: dockerfile
      args:
        - PLATFORM=x64
        - DOTNET_VERSION=8.0.408

  dotnet-sdk-x64-9:
    # https://dotnet.microsoft.com/en-us/download/dotnet/9.0
    image: amaic/devcontainer-dotnet-sdk:x64-9
    build:
      context: .
      dockerfile: dockerfile
      args:
        - PLATFORM=x64
        - DOTNET_VERSION=9.0.203
