FROM mcr.microsoft.com/devcontainers/base:ubuntu

RUN apt-get update && apt-get upgrade -y

WORKDIR /install

ARG PLATFORM
ARG DOTNET_VERSION

RUN <<"EOD"

wget https://builds.dotnet.microsoft.com/dotnet/Sdk/${DOTNET_VERSION}/dotnet-sdk-${DOTNET_VERSION}-linux-${PLATFORM}.tar.gz \
--output-document=dotnet-sdk.tar.gz

mkdir /opt/dotnet

tar \
--extract \
--gunzip \
--file=dotnet-sdk.tar.gz \
--directory=/opt/dotnet

EOD

COPY <<"EOD" /etc/bash_completion.d/dotnet

# bash parameter completion for the dotnet CLI

function _dotnet_bash_complete()
{
  local cur="${COMP_WORDS[COMP_CWORD]}" IFS=$'\n' # On Windows you may need to use use IFS=$'\r\n'
  local candidates

  read -d '' -ra candidates < <(dotnet complete --position "${COMP_POINT}" "${COMP_LINE}" 2>/dev/null)

  read -d '' -ra COMPREPLY < <(compgen -W "${candidates[*]:-}" -- "$cur")
}

complete -f -F _dotnet_bash_complete dotnet

EOD

RUN rm --recursive --force /install

ENV PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/dotnet"
ENV DOTNET_ROOT="/opt/dotnet"

USER vscode
WORKDIR /home/vscode/work

