FROM mcr.microsoft.com/dotnet/sdk:8.0 AS v8

RUN apt update && apt upgrade -y
RUN apt install -y bash-completion jq yq

RUN <<"EOD"
cat <<"EOF" > ~/.bashrc
# bash parameter completion for the dotnet CLI

function _dotnet_bash_complete()
{
  local cur="${COMP_WORDS[COMP_CWORD]}" IFS=$'\n' # On Windows you may need to use use IFS=$'\r\n'
  local candidates

  read -d '' -ra candidates < <(dotnet complete --position "${COMP_POINT}" "${COMP_LINE}" 2>/dev/null)

  read -d '' -ra COMPREPLY < <(compgen -W "${candidates[*]:-}" -- "$cur")
}

complete -f -F _dotnet_bash_complete dotnet
EOF
EOD
