FROM ubuntu:latest

RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y bash-completion git golang

RUN <<"DOCKERFILE_EOD"

cat <<-"EOD" >> ~/.bashrc

	if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
   		. /etc/bash_completion
	fi

	export GOBIN=~/go/bin
	export PATH=$PATH:~/go/bin

EOD

DOCKERFILE_EOD

RUN <<"DOCKERFILE_EOD"

go install golang.org/x/tools/gopls@latest 
go install github.com/go-delve/delve/cmd/dlv@latest 
go install honnef.co/go/tools/cmd/staticcheck@latest

DOCKERFILE_EOD
