FROM ubuntu

SHELL [ "/bin/bash", "-c" ]

RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y bash-completion ca-certificates curl git

RUN echo 'source /etc/bash_completion' >> ~/.bashrc


RUN <<"DOCKERFILE_EOD"

install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
chmod a+r /etc/apt/keyrings/docker.asc

echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
  $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
  tee /etc/apt/sources.list.d/docker.list > /dev/null
apt-get update

apt-get install -y docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

echo 'source <(docker completion bash)' > /etc/bash_completion.d/docker

DOCKERFILE_EOD


RUN apt-get install -y build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev curl git libncursesw5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev


ARG PYTHON_VERSION=3.11.8
RUN <<"DOCKERFILE_EOD"

curl https://pyenv.run | bash

cat <<-"BASH_EOD" | tee --append ~/.bashrc ~/.profile
	export PYENV_ROOT="$HOME/.pyenv"
	[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
	eval "$(pyenv init - bash)"
BASH_EOD

export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init - bash)"

pyenv install ${PYTHON_VERSION}
pyenv global ${PYTHON_VERSION}

DOCKERFILE_EOD


RUN <<"DOCKERFILE_EOD"

apt-get install -y pipx
pipx ensurepath

DOCKERFILE_EOD


RUN pipx install poetry


RUN <<"DOCKERFILE_EOD"

apt-get install -y groff unzip

curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
unzip awscliv2.zip
./aws/install

DOCKERFILE_EOD